### ISSUE TITLE
Logo offer for Watermaker

### ISSUE THREAD

**Issue by familqasimov** [SloCompTech/Watermarker#1]
Hi friend. I would like to offer logo. I can give you all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/41934930-187e5378-7999-11e8-991a-0e17c2097b25.png)

Best regard
Famil

**Comment by SloCompTech** [comment]
Wow!
Very nice design. Good logo. Would you be able to create different sizes of logo and one in ICO format and replace exsisting logo in `img` folder ?

**Comment by familqasimov** [comment]
Hi. Please select, what logo did you like.

**Comment by familqasimov** [comment]
Here you go. both logos sizes and an ico format.
https://drive.google.com/open?id=1AYdFcpLalsPkCc1gpw_Et2ulDCoYymw2

**Comment by familqasimov** [comment]
Can I send PR for logo?

**Comment by SloCompTech** [comment]
Thanks, I will at them ASAP to repositroy

**Comment by SloCompTech** [comment]
of coure you can, just put images in img folder and replace existing

**Comment by familqasimov** [comment]
Please write to me, for which of these two logos I send PR

**Comment by SloCompTech** [comment]
Left
